CUR_DIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

TEST_TARGET := tb_pe_top
TEST_ARGS ?= -g2005-sv
TEST_INCLUDE_DIR += $(TOP_DIR)/rtl/include

TEST_SRC += $(TOP_DIR)/rtl/PE_Core/PE_top/pe_top.v
TEST_SRC += $(TOP_DIR)/rtl/PE_Core/PE_ctrl/pe_ctrl.v
TEST_SRC += $(TOP_DIR)/rtl/PE_Core/PE/pe.v
TEST_SRC += $(TOP_DIR)/rtl/PE_Core/PE_router/pe_router.v
TEST_SRC += $(CUR_DIR)/tb_pe_top.v