
CUR_DIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

TEST_TARGET := rom_node
TEST_ARGS ?=
TEST_INCLUDE_DIR += -I$(TOP_DIR)/rtl/rom
TEST_SRC += $(TOP_DIR)/rtl/rom/flash_controller.v
TEST_SRC += $(TOP_DIR)/rtl/rom/rom_module.v
TEST_SRC += $(TOP_DIR)/rtl/rom/rom_ring_node.v
TEST_SRC += $(TOP_DIR)/rtl/rom/rom_node.v
TEST_SRC += $(CUR_DIR)/tb_rom_node.v
