
CUR_DIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

TEST_TARGET := riscv_cpu
TEST_ARGS ?= -g2005-sv
TEST_INCLUDE_DIR += -I$(TOP_DIR)/rtl/riscv
TEST_SRC += $(TOP_DIR)/rtl/core/riscv/riscv_cpu.v
TEST_SRC += $(TOP_DIR)/rtl/core/riscv/control_unit.v
TEST_SRC += $(TOP_DIR)/rtl/core/riscv/alu.v
TEST_SRC += $(TOP_DIR)/rtl/core/riscv/regfile.v
TEST_SRC += $(TOP_DIR)/rtl/core/riscv/hazard_detection.v
TEST_SRC += $(TOP_DIR)/rtl/core/riscv/branch_unit.v
TEST_SRC += $(TOP_DIR)/rtl/core/riscv/exception_handler.v
TEST_SRC += $(TOP_DIR)/rtl/core/riscv/csr_registers.v
TEST_SRC += $(TOP_DIR)/rtl/core/riscv/exception_detect.v
TEST_SRC += $(TOP_DIR)/rtl/core/riscv/interrupt_controller.v
TEST_SRC += $(TOP_DIR)/rtl/core/riscv/memory_mapped_timer.v
TEST_SRC += $(TOP_DIR)/rtl/core/riscv/timer_core.v
TEST_SRC += $(CUR_DIR)/tb_riscv_cpu.v
