
CUR_DIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

TEST_TARGET := gpio_node
TEST_ARGS ?=
TEST_INCLUDE_DIR += -I$(TOP_DIR)/rtl/gpio
TEST_SRC += $(TOP_DIR)/rtl/gpio/gpio_params.v
TEST_SRC += $(TOP_DIR)/rtl/gpio/gpio_module.v
TEST_SRC += $(TOP_DIR)/rtl/gpio/gpio_ring_node.v
TEST_SRC += $(TOP_DIR)/rtl/gpio/gpio_node.v
TEST_SRC += $(CUR_DIR)/tb_gpio_node.v
