
CUR_DIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

TEST_TARGET := tb_pe_controller
TEST_ARGS ?= -g2005-sv
TEST_INCLUDE_DIR += -I$(TOP_DIR)/rtl/include

TEST_SRC += $(TOP_DIR)/rtl/PE_Core/PE_ctrl/pe_ctrl.v
TEST_SRC += $(CUR_DIR)/tb_pe_controller.v