
CUR_DIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

TEST_TARGET := ring_node_demo
TEST_ARGS ?= -g2005-sv
TEST_INCLUDE_DIR += -I$(TOP_DIR)/rtl/bus/ring
TEST_SRC += $(TOP_DIR)/rtl/bus/ring/ring_bus_node.v
TEST_SRC += $(TOP_DIR)/rtl/bus/ring/ring_bus.v
TEST_SRC += $(CUR_DIR)/ring_node_demo_memory_device.v
TEST_SRC += $(CUR_DIR)/ring_node_demo_uart.v
TEST_SRC += $(CUR_DIR)/ring_request_node_demo.v
TEST_SRC += $(CUR_DIR)/ring_response_node_demo.v
TEST_SRC += $(CUR_DIR)/tb_ring_node_demo.v
