
CUR_DIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

TEST_TARGET := riscv_cache
TEST_ARGS ?= -g2005-sv
TEST_INCLUDE_DIR += -I$(TOP_DIR)/rtl/riscv

TEST_SRC += $(TOP_DIR)/rtl/core/riscv/cache_arbiter.v
TEST_SRC += $(TOP_DIR)/rtl/core/riscv/cache_system.v
TEST_SRC += $(TOP_DIR)/rtl/core/riscv/l1_icache.v
TEST_SRC += $(TOP_DIR)/rtl/core/riscv/l1_dcache.v
TEST_SRC += $(TOP_DIR)/rtl/core/riscv/l2_cache.v
TEST_SRC += $(TOP_DIR)/rtl/core/riscv/l2_cache_external_flash.v
TEST_SRC += $(TOP_DIR)/rtl/core/riscv/riscv_cpu_with_cache.v
TEST_SRC += $(TOP_DIR)/rtl/core/riscv/riscv_cpu.v
TEST_SRC += $(TOP_DIR)/rtl/core/riscv/control_unit.v
TEST_SRC += $(TOP_DIR)/rtl/core/riscv/alu.v
TEST_SRC += $(TOP_DIR)/rtl/core/riscv/regfile.v
TEST_SRC += $(TOP_DIR)/rtl/core/riscv/hazard_detection.v
TEST_SRC += $(TOP_DIR)/rtl/core/riscv/branch_unit.v
TEST_SRC += $(TOP_DIR)/rtl/core/riscv/exception_handler.v
TEST_SRC += $(TOP_DIR)/rtl/core/riscv/csr_registers.v
TEST_SRC += $(TOP_DIR)/rtl/core/riscv/exception_detect.v
TEST_SRC += $(TOP_DIR)/rtl/core/riscv/interrupt_controller.v
TEST_SRC += $(TOP_DIR)/rtl/core/riscv/flash_interface.v

TEST_SRC += $(CUR_DIR)/tb_cache_system.v
