
CUR_DIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

TEST_TARGET := riscv_timer
TEST_ARGS ?= -g2005-sv
TEST_INCLUDE_DIR += -I$(TOP_DIR)/rtl/riscv
TEST_SRC += $(TOP_DIR)/rtl/core/riscv/timer_core.v
TEST_SRC += $(TOP_DIR)/rtl/core/riscv/memory_mapped_timer.v
TEST_SRC += $(TOP_DIR)/rtl/core/riscv/csr_timer.v
TEST_SRC += $(TOP_DIR)/rtl/core/riscv/riscv_timer.v

TEST_SRC += $(TOP_DIR)/rtl/core/riscv/memory_controller.v
TEST_SRC += $(TOP_DIR)/rtl/core/riscv/ram.v
TEST_SRC += $(TOP_DIR)/rtl/core/riscv/rom.v
TEST_SRC += $(TOP_DIR)/rtl/core/riscv/flash.v
TEST_SRC += $(TOP_DIR)/rtl/core/riscv/memory_system.v
TEST_SRC += $(CUR_DIR)/tb_memory_system.v
