
CUR_DIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

TEST_TARGET := spi_core
TEST_ARGS ?= -g2012
TEST_INCLUDE_DIR += -I$(TOP_DIR)/rtl/spi
TEST_SRC += $(TOP_DIR)/rtl/spi/spi_core.v
TEST_SRC += $(TOP_DIR)/rtl/spi/spi_params.v
TEST_SRC += $(CUR_DIR)/tb_spi_controller.v