
CUR_DIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

TEST_TARGET := pe_controller
TEST_ARGS ?=
TEST_INCLUDE_DIR += -I$(TOP_DIR)/rtl/SynapticChip/PE_ctrl
TEST_SRC += $(TOP_DIR)/rtl/SynapticChip/PE_ctrl/pe_ctrl_params.v
TEST_SRC += $(TOP_DIR)/rtl/SynapticChip/PE_ctrl/pe_ctrl.v
TEST_SRC += $(TOP_DIR)/rtl/SynapticChip/PE_ctrl/pe_ctrl_route_config.v
TEST_SRC += $(CUR_DIR)/simple_pe.v
TEST_SRC += $(CUR_DIR)/tb_pe_controller.v
