
CUR_DIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

TEST_TARGET := top_system
TEST_ARGS ?= -g2005-sv

# common
TEST_INCLUDE_DIR += -I$(TOP_DIR)/rtl/common
TEST_SRC += $(TOP_DIR)/rtl/common/simple_fifo.v

# bus
TEST_INCLUDE_DIR += -I$(TOP_DIR)/rtl/bus/ring
TEST_SRC += $(TOP_DIR)/rtl/bus/ring/ring_bus_arbiter.v
TEST_SRC += $(TOP_DIR)/rtl/bus/ring/ring_bus_node.v
TEST_SRC += $(TOP_DIR)/rtl/bus/ring/ring_bus.v
TEST_SRC += $(TOP_DIR)/rtl/bus/ring/ring_single_bus.v

# core
TEST_INCLUDE_DIR += -I$(TOP_DIR)/rtl/core
TEST_SRC += $(TOP_DIR)/rtl/core/riscv_core.v
TEST_SRC += $(TOP_DIR)/rtl/core/riscv_bus_interface.v
TEST_SRC += $(TOP_DIR)/rtl/core/riscv_ring_node.v
TEST_SRC += $(TOP_DIR)/rtl/core/riscv_system.v

TEST_CPU_SRC += $(TOP_DIR)/rtl/core/riscv/riscv_cpu.v
TEST_CPU_SRC += $(TOP_DIR)/rtl/core/riscv/control_unit.v
TEST_CPU_SRC += $(TOP_DIR)/rtl/core/riscv/alu.v
TEST_CPU_SRC += $(TOP_DIR)/rtl/core/riscv/regfile.v
TEST_CPU_SRC += $(TOP_DIR)/rtl/core/riscv/hazard_detection.v
TEST_CPU_SRC += $(TOP_DIR)/rtl/core/riscv/branch_unit.v
TEST_CPU_SRC += $(TOP_DIR)/rtl/core/riscv/exception_handler.v
TEST_CPU_SRC += $(TOP_DIR)/rtl/core/riscv/csr_registers.v
TEST_CPU_SRC += $(TOP_DIR)/rtl/core/riscv/exception_detect.v
TEST_CPU_SRC += $(TOP_DIR)/rtl/core/riscv/interrupt_controller.v

TEST_MEMORY_SRC += $(TOP_DIR)/rtl/core/riscv/memory_controller.v
TEST_MEMORY_SRC += $(TOP_DIR)/rtl/core/riscv/ram.v

TEST_TIMER_SRC += $(TOP_DIR)/rtl/core/riscv/csr_timer.v
TEST_TIMER_SRC += $(TOP_DIR)/rtl/core/riscv/memory_mapped_timer.v
TEST_TIMER_SRC += $(TOP_DIR)/rtl/core/riscv/timer_core.v

TEST_SOC_SRC += $(TOP_DIR)/rtl/core/riscv/riscv_soc.v

TEST_CACHE_SRC += $(TOP_DIR)/rtl/core/riscv/cache_arbiter.v
TEST_CACHE_SRC += $(TOP_DIR)/rtl/core/riscv/cache_system.v
TEST_CACHE_SRC += $(TOP_DIR)/rtl/core/riscv/l1_icache.v
TEST_CACHE_SRC += $(TOP_DIR)/rtl/core/riscv/l1_dcache.v
TEST_CACHE_SRC += $(TOP_DIR)/rtl/core/riscv/l2_cache.v
TEST_CACHE_SRC += $(TOP_DIR)/rtl/core/riscv/flash_interface.v

TEST_SRC += $(TEST_CPU_SRC) $(TEST_CACHE_SRC) $(TEST_MEMORY_SRC) $(TEST_TIMER_SRC) $(TEST_SOC_SRC)

# ram
TEST_INCLUDE_DIR += -I$(TOP_DIR)/rtl/ram
TEST_SRC += $(TOP_DIR)/rtl/ram/ram_module.v
TEST_SRC += $(TOP_DIR)/rtl/ram/ram_ring_node.v
TEST_SRC += $(TOP_DIR)/rtl/ram/ram_node.v

# rom
TEST_INCLUDE_DIR += -I$(TOP_DIR)/rtl/rom
TEST_SRC += $(TOP_DIR)/rtl/rom/flash_controller.v
TEST_SRC += $(TOP_DIR)/rtl/rom/rom_module.v
TEST_SRC += $(TOP_DIR)/rtl/rom/rom_ring_node.v
TEST_SRC += $(TOP_DIR)/rtl/rom/rom_node.v

# PE
TEST_INCLUDE_DIR += -I$(TOP_DIR)/rtl/SynapticChip/PE
TEST_SRC += $(TOP_DIR)/rtl/SynapticChip/PE/pe_params.v
TEST_SRC += $(TOP_DIR)/rtl/SynapticChip/PE/pe_core.v
TEST_SRC += $(TOP_DIR)/rtl/SynapticChip/PE/pe_node.v

# PE controller
TEST_INCLUDE_DIR += -I$(TOP_DIR)/rtl/SynapticChip/PE_ctrl
TEST_SRC += $(TOP_DIR)/rtl/SynapticChip/PE_ctrl/pe_ctrl_params.v
TEST_SRC += $(TOP_DIR)/rtl/SynapticChip/PE_ctrl/pe_ctrl.v
TEST_SRC += $(TOP_DIR)/rtl/SynapticChip/PE_ctrl/pe_ctrl_route_config.v

# PE router
TEST_INCLUDE_DIR += -I$(TOP_DIR)/rtl/SynapticChip/router
TEST_SRC += $(TOP_DIR)/rtl/SynapticChip/router/pe_router_core.v
TEST_SRC += $(TOP_DIR)/rtl/SynapticChip/router/pe_router_config.v
TEST_SRC += $(TOP_DIR)/rtl/SynapticChip/router/pe_router_top.v

# uart
TEST_INCLUDE_DIR += -I$(TOP_DIR)/rtl/uart
TEST_SRC += $(TOP_DIR)/rtl/uart/uart_params.v
TEST_SRC += $(TOP_DIR)/rtl/uart/uart_core.v
TEST_SRC += $(TOP_DIR)/rtl/uart/uart_ring_node.v
TEST_SRC += $(TOP_DIR)/rtl/uart/uart_node.v

# gpio
TEST_INCLUDE_DIR += -I$(TOP_DIR)/rtl/gpio
TEST_SRC += $(TOP_DIR)/rtl/gpio/gpio_params.v
TEST_SRC += $(TOP_DIR)/rtl/gpio/gpio_module.v
TEST_SRC += $(TOP_DIR)/rtl/gpio/gpio_ring_node.v
TEST_SRC += $(TOP_DIR)/rtl/gpio/gpio_node.v

# jtag
TEST_INCLUDE_DIR += -I$(TOP_DIR)/rtl/jtag
TEST_SRC += $(TOP_DIR)/rtl/jtag/jtag_params.v
TEST_SRC += $(TOP_DIR)/rtl/jtag/jtag_tap.v
TEST_SRC += $(TOP_DIR)/rtl/jtag/jtag_ring_node.v
TEST_SRC += $(TOP_DIR)/rtl/jtag/jtag_node.v

# Synaptic Core
TEST_INCLUDE_DIR += -I$(TOP_DIR)/rtl/SynapticChip/top
TEST_SRC += $(TOP_DIR)/rtl/SynapticChip/top/synaptic_core.v

# top
TEST_INCLUDE_DIR += -I$(TOP_DIR)/rtl/top
TEST_SRC += $(TOP_DIR)/rtl/top/top_system.v

TEST_SRC += $(CUR_DIR)/tb_top_system.v
