
CUR_DIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

TEST_TARGET := top_system
TEST_ARGS ?= -g2005-sv

# common
TEST_INCLUDE_DIR += -I$(TOP_DIR)/rtl/common
TEST_SRC += $(TOP_DIR)/rtl/common/fifo.v
TEST_SRC += $(TOP_DIR)/rtl/common/cache.v

# bus
TEST_INCLUDE_DIR += -I$(TOP_DIR)/rtl/bus/ring
TEST_SRC += $(TOP_DIR)/rtl/bus/ring/ring_bus_arbiter.v
TEST_SRC += $(TOP_DIR)/rtl/bus/ring/ring_bus_node.v
TEST_SRC += $(TOP_DIR)/rtl/bus/ring/ring_bus.v
TEST_SRC += $(TOP_DIR)/rtl/bus/ring/ring_single_bus.v
TEST_SRC += $(TOP_DIR)/rtl/bus/address_decoder.v
TEST_SRC += $(TOP_DIR)/rtl/bus/mmio_subsystem.v
TEST_SRC += $(TOP_DIR)/rtl/bus/system_bus_arbiter.v
TEST_SRC += $(TOP_DIR)/rtl/bus/uart.v
TEST_SRC += $(TOP_DIR)/rtl/bus/bus_top.v

# cpu
TEST_INCLUDE_DIR += -I$(TOP_DIR)/rtl/cpu
TEST_INCLUDE_DIR += -I$(TOP_DIR)/rtl/cpu/riscv
TEST_INCLUDE_DIR += -I$(TOP_DIR)/rtl/cpu/riscv/riscv64
TEST_SRC += $(TOP_DIR)/rtl/cpu/riscv/riscv64/clock_reset_gen.v
TEST_SRC += $(TOP_DIR)/rtl/cpu/riscv/riscv64/execution.v
TEST_SRC += $(TOP_DIR)/rtl/cpu/riscv/riscv64/hazard_detection.v
TEST_SRC += $(TOP_DIR)/rtl/cpu/riscv/riscv64/instruction_decode.v
TEST_SRC += $(TOP_DIR)/rtl/cpu/riscv/riscv64/instruction_fetch.v
TEST_SRC += $(TOP_DIR)/rtl/cpu/riscv/riscv64/memory_access.v
TEST_SRC += $(TOP_DIR)/rtl/cpu/riscv/riscv64/memory_arbiter.v
TEST_SRC += $(TOP_DIR)/rtl/cpu/riscv/riscv64/register_file.v
TEST_SRC += $(TOP_DIR)/rtl/cpu/riscv/riscv64/riscv64_core.v
TEST_SRC += $(TOP_DIR)/rtl/cpu/riscv/riscv64/write_back.v
TEST_SRC += $(TOP_DIR)/rtl/cpu/riscv/riscv_bus_interface.v
TEST_SRC += $(TOP_DIR)/rtl/cpu/riscv/riscv_ring_node.v
TEST_SRC += $(TOP_DIR)/rtl/cpu/cpu_top.v

# PE
TEST_INCLUDE_DIR += -I$(TOP_DIR)/rtl/PE_Core/PE
TEST_SRC += $(TOP_DIR)/rtl/PE_Core/PE/pe_params.v
TEST_SRC += $(TOP_DIR)/rtl/PE_Core/PE/pe_core.v
TEST_SRC += $(TOP_DIR)/rtl/PE_Core/PE/pe_node.v

# PE controller
TEST_INCLUDE_DIR += -I$(TOP_DIR)/rtl/PE_Core/PE_ctrl
TEST_SRC += $(TOP_DIR)/rtl/PE_Core/PE_ctrl/pe_ctrl_params.v
TEST_SRC += $(TOP_DIR)/rtl/PE_Core/PE_ctrl/pe_ctrl.v
TEST_SRC += $(TOP_DIR)/rtl/PE_Core/PE_ctrl/pe_ctrl_route_config.v

# PE PE_router
TEST_INCLUDE_DIR += -I$(TOP_DIR)/rtl/PE_Core/PE_router
TEST_SRC += $(TOP_DIR)/rtl/PE_Core/PE_router/pe_router_core.v
TEST_SRC += $(TOP_DIR)/rtl/PE_Core/PE_router/pe_router_config.v
TEST_SRC += $(TOP_DIR)/rtl/PE_Core/PE_router/pe_router_top.v

# uart
TEST_INCLUDE_DIR += -I$(TOP_DIR)/rtl/uart
TEST_SRC += $(TOP_DIR)/rtl/uart/uart_params.v
TEST_SRC += $(TOP_DIR)/rtl/uart/uart_core.v
TEST_SRC += $(TOP_DIR)/rtl/uart/uart_ring_node.v
TEST_SRC += $(TOP_DIR)/rtl/uart/uart_node.v

# gpio
TEST_INCLUDE_DIR += -I$(TOP_DIR)/rtl/gpio
TEST_SRC += $(TOP_DIR)/rtl/gpio/gpio_params.v
TEST_SRC += $(TOP_DIR)/rtl/gpio/gpio_module.v
TEST_SRC += $(TOP_DIR)/rtl/gpio/gpio_ring_node.v
TEST_SRC += $(TOP_DIR)/rtl/gpio/gpio_node.v

# jtag
TEST_INCLUDE_DIR += -I$(TOP_DIR)/rtl/jtag
TEST_SRC += $(TOP_DIR)/rtl/jtag/jtag_params.v
TEST_SRC += $(TOP_DIR)/rtl/jtag/jtag_top.v
TEST_SRC += $(TOP_DIR)/rtl/jtag/jtag_ring_node.v
TEST_SRC += $(TOP_DIR)/rtl/jtag/jtag_node.v

# Synaptic Core
TEST_INCLUDE_DIR += -I$(TOP_DIR)/rtl/PE_Core/PE_top
TEST_SRC += $(TOP_DIR)/rtl/PE_Core/PE_top/pe_top.v

# spi
TEST_INCLUDE_DIR += -I$(TOP_DIR)/rtl/spi
TEST_SRC += $(TOP_DIR)/rtl/spi/spi_core.v
TEST_SRC += $(TOP_DIR)/rtl/spi/spi_node.v
TEST_SRC += $(TOP_DIR)/rtl/spi/spi_ring_node.v

# top
TEST_INCLUDE_DIR += -I$(TOP_DIR)/rtl/top
TEST_SRC += $(TOP_DIR)/rtl/top/top_system.v

TEST_SRC += $(CUR_DIR)/tb_top_system.v