
CUR_DIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

TEST_TARGET := top_system
TEST_ARGS ?= -g2005-sv

# common
TEST_INCLUDE_DIR += -I$(TOP_DIR)/rtl/common
TEST_SRC += $(TOP_DIR)/rtl/common/simple_fifo.v
TEST_SRC += $(TOP_DIR)/rtl/common/cache.v

# bus
TEST_INCLUDE_DIR += -I$(TOP_DIR)/rtl/bus/ring
TEST_SRC += $(TOP_DIR)/rtl/bus/ring/ring_bus_arbiter.v
TEST_SRC += $(TOP_DIR)/rtl/bus/ring/ring_bus_node.v
TEST_SRC += $(TOP_DIR)/rtl/bus/ring/ring_bus.v
TEST_SRC += $(TOP_DIR)/rtl/bus/ring/ring_single_bus.v

# core
TEST_INCLUDE_DIR += -I$(TOP_DIR)/rtl/core
TEST_INCLUDE_DIR += -I$(TOP_DIR)/rtl/core/riscv
TEST_INCLUDE_DIR += -I$(TOP_DIR)/rtl/core/riscv/riscv64_multicore
TEST_SRC += $(TOP_DIR)/rtl/core/riscv/riscv64_multicore/address_decoder.v
TEST_SRC += $(TOP_DIR)/rtl/core/riscv/riscv64_multicore/cache_params.v
TEST_SRC += $(TOP_DIR)/rtl/core/riscv/riscv64_multicore/clock_reset_gen.v
TEST_SRC += $(TOP_DIR)/rtl/core/riscv/riscv64_multicore/execution.v
TEST_SRC += $(TOP_DIR)/rtl/core/riscv/riscv64_multicore/flash_controller.v
TEST_SRC += $(TOP_DIR)/rtl/core/riscv/riscv64_multicore/hazard_detection.v
TEST_SRC += $(TOP_DIR)/rtl/core/riscv/riscv64_multicore/instruction_decode.v
TEST_SRC += $(TOP_DIR)/rtl/core/riscv/riscv64_multicore/instruction_fetch.v
TEST_SRC += $(TOP_DIR)/rtl/core/riscv/riscv64_multicore/memory_access.v
TEST_SRC += $(TOP_DIR)/rtl/core/riscv/riscv64_multicore/memory_arbiter.v
TEST_SRC += $(TOP_DIR)/rtl/core/riscv/riscv64_multicore/mmio_subsystem.v
TEST_SRC += $(TOP_DIR)/rtl/core/riscv/riscv64_multicore/register_file.v
TEST_SRC += $(TOP_DIR)/rtl/core/riscv/riscv64_multicore/riscv64_core.v
TEST_SRC += $(TOP_DIR)/rtl/core/riscv/riscv64_multicore/riscv64_multicore.v
TEST_SRC += $(TOP_DIR)/rtl/core/riscv/riscv64_multicore/riscv64_soc.v
TEST_SRC += $(TOP_DIR)/rtl/core/riscv/riscv64_multicore/soc_params.v
TEST_SRC += $(TOP_DIR)/rtl/core/riscv/riscv64_multicore/system_bus_arbiter.v
TEST_SRC += $(TOP_DIR)/rtl/core/riscv/riscv64_multicore/uart.v
TEST_SRC += $(TOP_DIR)/rtl/core/riscv/riscv64_multicore/write_back.v
TEST_SRC += $(TOP_DIR)/rtl/core/riscv/riscv_bus_interface.v
TEST_SRC += $(TOP_DIR)/rtl/core/riscv/riscv_ring_node.v
TEST_SRC += $(TOP_DIR)/rtl/core/riscv/riscv_system.v

# PE
TEST_INCLUDE_DIR += -I$(TOP_DIR)/rtl/SynapticChip/PE
TEST_SRC += $(TOP_DIR)/rtl/SynapticChip/PE/pe_params.v
TEST_SRC += $(TOP_DIR)/rtl/SynapticChip/PE/pe_core.v
TEST_SRC += $(TOP_DIR)/rtl/SynapticChip/PE/pe_node.v

# PE controller
TEST_INCLUDE_DIR += -I$(TOP_DIR)/rtl/SynapticChip/PE_ctrl
TEST_SRC += $(TOP_DIR)/rtl/SynapticChip/PE_ctrl/pe_ctrl_params.v
TEST_SRC += $(TOP_DIR)/rtl/SynapticChip/PE_ctrl/pe_ctrl.v
TEST_SRC += $(TOP_DIR)/rtl/SynapticChip/PE_ctrl/pe_ctrl_route_config.v

# PE router
TEST_INCLUDE_DIR += -I$(TOP_DIR)/rtl/SynapticChip/router
TEST_SRC += $(TOP_DIR)/rtl/SynapticChip/router/pe_router_core.v
TEST_SRC += $(TOP_DIR)/rtl/SynapticChip/router/pe_router_config.v
TEST_SRC += $(TOP_DIR)/rtl/SynapticChip/router/pe_router_top.v

# uart
TEST_INCLUDE_DIR += -I$(TOP_DIR)/rtl/uart
TEST_SRC += $(TOP_DIR)/rtl/uart/uart_params.v
TEST_SRC += $(TOP_DIR)/rtl/uart/uart_core.v
TEST_SRC += $(TOP_DIR)/rtl/uart/uart_ring_node.v
TEST_SRC += $(TOP_DIR)/rtl/uart/uart_node.v

# gpio
TEST_INCLUDE_DIR += -I$(TOP_DIR)/rtl/gpio
TEST_SRC += $(TOP_DIR)/rtl/gpio/gpio_params.v
TEST_SRC += $(TOP_DIR)/rtl/gpio/gpio_module.v
TEST_SRC += $(TOP_DIR)/rtl/gpio/gpio_ring_node.v
TEST_SRC += $(TOP_DIR)/rtl/gpio/gpio_node.v

# jtag
TEST_INCLUDE_DIR += -I$(TOP_DIR)/rtl/jtag
TEST_SRC += $(TOP_DIR)/rtl/jtag/jtag_params.v
TEST_SRC += $(TOP_DIR)/rtl/jtag/jtag_tap.v
TEST_SRC += $(TOP_DIR)/rtl/jtag/jtag_ring_node.v
TEST_SRC += $(TOP_DIR)/rtl/jtag/jtag_node.v

# Synaptic Core
TEST_INCLUDE_DIR += -I$(TOP_DIR)/rtl/SynapticChip/top
TEST_SRC += $(TOP_DIR)/rtl/SynapticChip/top/synaptic_core.v

# spi
TEST_INCLUDE_DIR += -I$(TOP_DIR)/rtl/spi
TEST_SRC += $(TOP_DIR)/rtl/spi/spi_core.v
TEST_SRC += $(TOP_DIR)/rtl/spi/spi_node.v
TEST_SRC += $(TOP_DIR)/rtl/spi/spi_ring_node.v

# top
TEST_INCLUDE_DIR += -I$(TOP_DIR)/rtl/top
TEST_SRC += $(TOP_DIR)/rtl/top/top_system.v

TEST_SRC += $(CUR_DIR)/tb_top_system.v
