CUR_DIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

TEST_TARGET := riscv64_core
TEST_ARGS ?= -g2012
TEST_INCLUDE_DIR += -I$(TOP_DIR)/rtl/cpu
TEST_INCLUDE_DIR += -I$(TOP_DIR)/rtl/cpu/riscv/riscv64
TEST_INCLUDE_DIR += -I$(TOP_DIR)/rtl/common

TEST_SRC += $(TOP_DIR)/rtl/cpu/riscv/riscv64/riscv64_core.v
TEST_SRC += $(TOP_DIR)/rtl/cpu/riscv/riscv64/riscv64_instruction_fetch.v
TEST_SRC += $(TOP_DIR)/rtl/cpu/riscv/riscv64/riscv64_instruction_decode.v
TEST_SRC += $(TOP_DIR)/rtl/cpu/riscv/riscv64/riscv64_execution.v
TEST_SRC += $(TOP_DIR)/rtl/cpu/riscv/riscv64/riscv64_memory_access.v
TEST_SRC += $(TOP_DIR)/rtl/cpu/riscv/riscv64/riscv64_write_back.v
TEST_SRC += $(TOP_DIR)/rtl/cpu/riscv/riscv64/riscv64_register_file.v
TEST_SRC += $(TOP_DIR)/rtl/cpu/riscv/riscv64/riscv64_hazard_detection.v
TEST_SRC += $(TOP_DIR)/rtl/common/cache.v
TEST_SRC += $(TOP_DIR)/rtl/cpu/riscv/riscv64/riscv64_soc_params.v
TEST_SRC += $(TOP_DIR)/rtl/cpu/cache_params.v
TEST_SRC += $(TOP_DIR)/rtl/cpu/cache_system_params.v

TEST_SRC += $(CUR_DIR)/tb_riscv64_core.v
