CUR_DIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

TEST_TARGET := obi_to_apb_bridge
TEST_ARGS ?= -g2005-sv
TEST_INCLUDE_DIR +=

TEST_SRC += $(CUR_DIR)/obi_to_apb_bridge.v
TEST_SRC += $(CUR_DIR)/apb_ram.v
TEST_SRC += $(CUR_DIR)/obi_apb_system_tb.v
