
CUR_DIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

TEST_TARGET := riscv_timer
TEST_ARGS ?= -g2005-sv
TEST_INCLUDE_DIR += -I$(TOP_DIR)/rtl/riscv

TEST_CPU_SRC += $(TOP_DIR)/rtl/core/riscv/riscv_cpu.v
TEST_CPU_SRC += $(TOP_DIR)/rtl/core/riscv/control_unit.v
TEST_CPU_SRC += $(TOP_DIR)/rtl/core/riscv/alu.v
TEST_CPU_SRC += $(TOP_DIR)/rtl/core/riscv/regfile.v
TEST_CPU_SRC += $(TOP_DIR)/rtl/core/riscv/hazard_detection.v
TEST_CPU_SRC += $(TOP_DIR)/rtl/core/riscv/branch_unit.v
TEST_CPU_SRC += $(TOP_DIR)/rtl/core/riscv/exception_handler.v
TEST_CPU_SRC += $(TOP_DIR)/rtl/core/riscv/csr_registers.v
TEST_CPU_SRC += $(TOP_DIR)/rtl/core/riscv/exception_detect.v
TEST_CPU_SRC += $(TOP_DIR)/rtl/core/riscv/interrupt_controller.v

TEST_MEMORY_SRC += $(TOP_DIR)/rtl/core/riscv/memory_controller.v
TEST_MEMORY_SRC += $(TOP_DIR)/rtl/core/riscv/ram.v
TEST_MEMORY_SRC += $(TOP_DIR)/rtl/core/riscv/rom.v
TEST_MEMORY_SRC += $(TOP_DIR)/rtl/core/riscv/flash.v
TEST_MEMORY_SRC += $(TOP_DIR)/rtl/core/riscv/memory_system.v

TEST_TIMER_SRC += $(TOP_DIR)/rtl/core/riscv/csr_timer.v
TEST_TIMER_SRC += $(TOP_DIR)/rtl/core/riscv/memory_mapped_timer.v
TEST_TIMER_SRC += $(TOP_DIR)/rtl/core/riscv/timer_core.v

TEST_SOC_SRC += $(TOP_DIR)/rtl/core/riscv/riscv_soc.v

TEST_CACHE_SRC += $(TOP_DIR)/rtl/core/riscv/cache_arbiter.v
TEST_CACHE_SRC += $(TOP_DIR)/rtl/core/riscv/cache_system.v
TEST_CACHE_SRC += $(TOP_DIR)/rtl/core/riscv/l1_icache.v
TEST_CACHE_SRC += $(TOP_DIR)/rtl/core/riscv/l1_dcache.v
TEST_CACHE_SRC += $(TOP_DIR)/rtl/core/riscv/l2_cache.v
TEST_CACHE_SRC += $(TOP_DIR)/rtl/core/riscv/flash_interface.v

TEST_SRC += $(TEST_CPU_SRC) $(TEST_CACHE_SRC) $(TEST_MEMORY_SRC) $(TEST_TIMER_SRC) $(TEST_SOC_SRC)
TEST_SRC += $(CUR_DIR)/tb_riscv_soc.v
