
CUR_DIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

SIM_CYCLE ?= 1000000
ROM_PRG   ?= program.hex
RAM_PRG   ?= data_bss.hex

TEST_TARGET := top_system
TEST_ARGS ?= -g2005-sv -DROM_PRG=\"$(ROM_PRG)\" -DRAM_PRG=\"$(RAM_PRG)\" -DSIM_CYCLE=$(SIM_CYCLE)

TEST_INCLUDE_DIR += $(RTL_INCLUDE_DIR)

TEST_SRC += $(RTL_SRC)

TEST_SRC += $(CUR_DIR)/test_spi_slave.v
TEST_SRC += $(CUR_DIR)/chip_top_test.v
