
CUR_DIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

SIM_CYCLE ?= 1000000
ROM_PRG   ?= program.hex
RAM_PRG   ?= data_bss.hex
BOOT_TYPE ?= 0

TEST_TARGET := top_system
TEST_ARGS ?= -g2005-sv -DROM_PRG=\"$(ROM_PRG)\" -DRAM_PRG=\"$(RAM_PRG)\" -DSIM_CYCLE=$(SIM_CYCLE) -DBOOT_TYPE=$(BOOT_TYPE)

TEST_INCLUDE_DIR += $(RTL_INCLUDE_DIR)

TEST_SRC += $(RTL_SRC)

TEST_SRC += $(CUR_DIR)/test_spi_slave.v
TEST_SRC += $(CUR_DIR)/qspi_flash_model.v
TEST_SRC += $(CUR_DIR)/MX25L6436F.v
TEST_SRC += $(CUR_DIR)/chip_top_test.v