
CUR_DIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

TEST_TARGET := router_node
TEST_ARGS ?=
TEST_INCLUDE_DIR += -I$(TOP_DIR)/rtl/PE_Core/PE_router
TEST_SRC += $(TOP_DIR)/rtl/PE_Core/PE_router/pe_router_core.v
TEST_SRC += $(TOP_DIR)/rtl/PE_Core/PE_router/pe_router_config.v
TEST_SRC += $(TOP_DIR)/rtl/PE_Core/PE_router/pe_router_top.v
TEST_SRC += $(CUR_DIR)/tb_router.v
