
CUR_DIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

TEST_TARGET := router_node
TEST_ARGS ?=
TEST_INCLUDE_DIR += $(TOP_DIR)/rtl/include

TEST_SRC += $(TOP_DIR)/rtl/PE_Core/PE_router/pe_router.v
TEST_SRC += $(CUR_DIR)/tb_router.v