
CUR_DIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

TEST_TARGET := ram_node
TEST_ARGS ?=
TEST_INCLUDE_DIR += -I$(TOP_DIR)/rtl/ram
TEST_SRC += $(TOP_DIR)/rtl/ram/ram_module.v
TEST_SRC += $(TOP_DIR)/rtl/ram/ram_ring_node.v
TEST_SRC += $(TOP_DIR)/rtl/ram/ram_node.v
TEST_SRC += $(CUR_DIR)/tb_ram_node.v
