
CUR_DIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

TEST_TARGET := ring_bus
TEST_ARGS ?=
TEST_INCLUDE_DIR += -I$(TOP_DIR)/rtl/bus
TEST_SRC += $(TOP_DIR)/rtl/bus/ring_bus_node.v
TEST_SRC += $(TOP_DIR)/rtl/bus/ring_bus.v
TEST_SRC += $(CUR_DIR)/tb_ring_bus.v
