
CUR_DIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

TEST_TARGET := jtag_top
TEST_ARGS ?=
TEST_INCLUDE_DIR += -I$(TOP_DIR)/rtl/jtag
TEST_SRC += $(TOP_DIR)/rtl/jtag/jtag_top.v
TEST_SRC += $(CUR_DIR)/tb_jtag_top.v