CUR_DIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

TEST_TARGET := fifo
TEST_ARGS ?= -g2012
TEST_INCLUDE_DIR += -I$(TOP_DIR)/rtl/common
TEST_SRC += $(TOP_DIR)/rtl/common/fifo.v

TEST_SRC += $(CUR_DIR)/tb_fifo.v